Revert Thread Locking
blevesearch/go-faiss pull request #27
Opened 2024-06-05 16:01 UTC by CascadingRadium

2024-06-05 16:47 UTC, abhinavdangeti commented
We cannot just do this because this was introduced to keep context to two successive CGO calls. I see your comment in the description, but you must either propose the faiss apis change here for this or drop making successive cgo calls to faiss within the same go-faiss API.

2024-06-05 16:52 UTC, abhinavdangeti requested changes
Comment above^

2024-06-06 03:56 UTC, Thejas-bhat commented
maybe an alternate approach over here could involve modifying the existing c_api funcs to have a `char** exception` passed from golang and in the c function you can populate this golang buffer with the message. so in a single c function call you'd be getting the exception message if there was an error. there wouldn't have to be any worry with respect to the buffer being local to a sepcific os thread now since the buffer is at golang's routine level (so the context would be maintained)

not sure if there are potential flaws in this one, but please let me know if this makes sense, thanks

2024-06-10 15:37 UTC, CascadingRadium commented
Yes that is the next TODO here
I have transferred this commit via cherry-pick to 
https://github.com/blevesearch/go-faiss/pull/28

2024-06-10 15:37 UTC, closed without merging